#!/usr/bin/env bash
set -Eeuo pipefail

# Preserve Docker service discovery while still allowing OpenConnect/vpnc-script
# to configure tunnel routes. The stock vpnc-script overwrites /etc/resolv.conf
# with VPN DNS servers, which bypasses Docker's embedded DNS (127.0.0.11) and
# breaks Compose service names such as `camofox` for containers sharing this
# VPN gateway network namespace.

log() {
  printf '[openconnect-dns-wrapper] %s\n' "$*" >&2
}

unique_domains() {
  awk '
    NF {
      for (i = 1; i <= NF; i++) {
        if ($i != "" && !seen[$i]++) {
          printf "%s%s", sep, $i
          sep = " "
        }
      }
    }
  '
}

search_domains() {
  {
    if [[ -r "$RESOLV_CONF" ]]; then
      awk '$1 == "search" { for (i = 2; i <= NF; i++) print $i } $1 == "domain" { print $2 }' "$RESOLV_CONF"
    fi
    if [[ -n "${CISCO_DEF_DOMAIN:-}" ]]; then
      printf '%s\n' "$CISCO_DEF_DOMAIN"
    fi
    if [[ -n "${CISCO_SPLIT_DNS:-}" ]]; then
      printf '%s\n' "$CISCO_SPLIT_DNS" | tr ',;' '  '
    fi
  } | unique_domains
}

preserve_docker_resolver() {
  local domains=""
  domains="$(search_domains)"

  local options_lines=()
  if [[ -r "$RESOLV_CONF" ]]; then
    mapfile -t options_lines < <(awk '$1 == "options" { print }' "$RESOLV_CONF")
  fi

  local tmp="${RESOLV_CONF}.$$"
  {
    printf '# Generated by openconnect-dns-wrapper.\n'
    printf '# Docker DNS is intentionally kept first so Compose service names keep resolving after VPN connect.\n'
    if ((${#options_lines[@]} > 0)); then
      printf '%s\n' "${options_lines[@]}"
    fi
    printf 'nameserver %s\n' "$DOCKER_DNS_SERVER"
    if [[ -n "$domains" ]]; then
      printf 'search %s\n' "$domains"
    fi
  } > "$tmp"

  # Docker bind-mounts /etc/resolv.conf in many containers. Replacing it with
  # rename(2) can fail with "Device or resource busy", so update it in place.
  cat "$tmp" > "$RESOLV_CONF"
  rm -f "$tmp"
  log "Preserved Docker DNS server ${DOCKER_DNS_SERVER}${domains:+ with search domains: ${domains}}."
}

main() {
  ORIGINAL_VPNC_SCRIPT="${VPN_VPNC_SCRIPT:-/usr/share/vpnc-scripts/vpnc-script}"
  RESOLV_CONF="${VPN_RESOLV_CONF:-/etc/resolv.conf}"
  DOCKER_DNS_SERVER="127.0.0.11"
  PRESERVE_DOCKER_DNS="${VPN_PRESERVE_DOCKER_DNS:-1}"

  if [[ "$PRESERVE_DOCKER_DNS" == "0" || "$PRESERVE_DOCKER_DNS" == "false" ]]; then
    exec "$ORIGINAL_VPNC_SCRIPT" "$@"
  fi

  local saved_internal_ip4_dns="${INTERNAL_IP4_DNS-}"
  local had_internal_ip4_dns=0
  if [[ ${INTERNAL_IP4_DNS+x} ]]; then
    had_internal_ip4_dns=1
  fi

  # The stock script only rewrites resolv.conf when INTERNAL_IP4_DNS is set.
  # Hide that variable from the child script, but leave all route-related VPN
  # variables intact so tunnel routes are still configured normally.
  export INTERNAL_IP4_DNS=
  set +e
  "$ORIGINAL_VPNC_SCRIPT" "$@"
  local status=$?
  set -e

  if ((had_internal_ip4_dns)); then
    export INTERNAL_IP4_DNS="$saved_internal_ip4_dns"
  else
    unset INTERNAL_IP4_DNS
  fi

  if ((status != 0)); then
    return "$status"
  fi

  case "${reason:-}" in
    connect|reconnect)
      preserve_docker_resolver
      ;;
  esac
}

main "$@"
