#!/usr/bin/env bash
set -Eeuo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

fake_vpnc_script="$tmpdir/fake-vpnc-script.sh"
resolv_conf="$tmpdir/resolv.conf"
env_capture="$tmpdir/env-capture"

cat > "$fake_vpnc_script" <<'FAKEVPNC'
#!/usr/bin/env bash
set -Eeuo pipefail
{
  printf 'INTERNAL_IP4_DNS=%s\n' "${INTERNAL_IP4_DNS-}"
  printf 'CISCO_SPLIT_INC=%s\n' "${CISCO_SPLIT_INC-}"
  printf 'CISCO_SPLIT_INC_0_ADDR=%s\n' "${CISCO_SPLIT_INC_0_ADDR-}"
} > "$VPN_TEST_ENV_CAPTURE"
# Simulate route setup succeeding. The real wrapper prevents the stock script
# from seeing INTERNAL_IP4_DNS, so it should not rewrite resolv.conf itself.
FAKEVPNC
chmod +x "$fake_vpnc_script"

cat > "$resolv_conf" <<'RESOLV'
# Generated by Docker Engine.
options ndots:0
nameserver 127.0.0.11
RESOLV

VPN_VPNC_SCRIPT="$fake_vpnc_script" \
VPN_RESOLV_CONF="$resolv_conf" \
VPN_TEST_ENV_CAPTURE="$env_capture" \
reason=connect \
INTERNAL_IP4_DNS="10.2.101.11" \
CISCO_DEF_DOMAIN="corp.example.test" \
CISCO_SPLIT_INC="1" \
CISCO_SPLIT_INC_0_ADDR="10.2.0.0" \
"$repo_root/openconnect-dns-wrapper.sh"

if ! grep -qx 'INTERNAL_IP4_DNS=' "$env_capture"; then
  echo "Expected child vpnc-script not to see INTERNAL_IP4_DNS" >&2
  cat "$env_capture" >&2
  exit 1
fi

if ! grep -qx 'CISCO_SPLIT_INC=1' "$env_capture" || ! grep -qx 'CISCO_SPLIT_INC_0_ADDR=10.2.0.0' "$env_capture"; then
  echo "Expected route-related split tunnel variables to reach child vpnc-script" >&2
  cat "$env_capture" >&2
  exit 1
fi

if ! grep -qx 'nameserver 127.0.0.11' "$resolv_conf"; then
  echo "Expected Docker DNS to be preserved" >&2
  cat "$resolv_conf" >&2
  exit 1
fi

if grep -q 'nameserver 10.2.101.11' "$resolv_conf"; then
  echo "Expected VPN DNS not to replace Docker DNS" >&2
  cat "$resolv_conf" >&2
  exit 1
fi

if ! grep -qx 'search corp.example.test' "$resolv_conf"; then
  echo "Expected VPN search domain to be retained" >&2
  cat "$resolv_conf" >&2
  exit 1
fi

if ! grep -qx 'options ndots:0' "$resolv_conf"; then
  echo "Expected Docker resolver options to be retained" >&2
  cat "$resolv_conf" >&2
  exit 1
fi

cat > "$resolv_conf" <<'RESOLV'
nameserver 127.0.0.11
RESOLV

VPN_VPNC_SCRIPT="$fake_vpnc_script" \
VPN_RESOLV_CONF="$resolv_conf" \
VPN_TEST_ENV_CAPTURE="$env_capture" \
VPN_PRESERVE_DOCKER_DNS=0 \
reason=connect \
INTERNAL_IP4_DNS="10.2.101.11" \
"$repo_root/openconnect-dns-wrapper.sh"

if ! grep -qx 'INTERNAL_IP4_DNS=10.2.101.11' "$env_capture"; then
  echo "Expected opt-out mode to pass INTERNAL_IP4_DNS to child vpnc-script" >&2
  cat "$env_capture" >&2
  exit 1
fi

echo "preserve Docker DNS tests passed"
